name: Supabase Keep Alive

on:
  schedule:
    # 每 3 天执行一次（UTC 0 点 → 北京时间早 8 点）
    - cron: "0 0 */3 * *"
  workflow_dispatch: # 手动触发按钮

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Supabase table
        run: |
          curl -s -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
               "https://zzglunzkgcolwhmwyzjo.supabase.co/rest/v1/meter_readings?limit=1"
