name: Supabase Keep Alive Test

on:
  schedule:
    # 每 5 分钟执行一次
    - cron: "*/5 * * * *"
  workflow_dispatch: # 支持手动运行

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase table
        run: |
          echo "=== Requesting Supabase API ==="
          # 发请求并保存响应
          STATUS=$(curl -s -o response.json -w "%{http_code}" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            "https://zzglunzkgcolwhmwyzjo.supabase.co/rest/v1/meter_readings?limit=1")
          
          echo "HTTP Status: $STATUS"
          echo "--- Response Body ---"
          cat response.json
          echo "--------------------"
          echo "=== Done ==="
